name: enpal_monitor
description: "An application for data monitoring of solar energy"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mocktail: ^1.0.4
  pretty_dio_logger: ^1.4.0
  fl_chart: ^0.69.2
  sqflite: ^2.4.1
  path: ^1.9.0

  #local packages
  enpal_design_system:
    path: ./enpal_design_system


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  dart_pre_commit: ^5.4.0
  bloc_test: ^9.1.7

flutter:

  uses-material-design: true

  assets:
    - assets/
