name: enpal_design_system
description: "A design system for enpal monitor app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: packages/enpal_design_system/fonts/lato/lato_regular.ttf
          weight: 400
        - asset: packages/enpal_design_system/fonts/lato/lato_bold.ttf
          weight: 500
